import Head from 'next/head'
import Splash from './splash.js'
import Auth from './auth.js'
import Notch from './notch.js'
import * as React from 'react'
import { Zoom } from '@mui/material'

export default function Home() {

const [showsplash,setSplash] = React.useState(true)
const [showauth,setAuth] = React.useState(false)
 
React.useEffect(() => {
setTimeout(() => {
  setAuth(true)
  setSplash(false)},2000)

  let secTimer = setInterval( () => {
    if (window.outerHeight == screen.height) {
      document.getElementById("container").style.borderRadius = "16px";
      document.getElementById("notchContainer").style = "color:#282828; background-color:#000; top:0px; border-top-left-radius:0px; border-top-right-radius:0px; padding:8px 68px;";
    } else {
      document.getElementById("container").style.borderRadius = "0px";
      document.getElementById("notchContainer").style = "";
    }
  },500)
  return () => clearInterval(secTimer);  
})

React.useEffect(() => {
  if(!showsplash) {
  setTimeout(() => {  
  document.getElementById("splash").style.display = "none";
  },500)
  } else {
  setTimeout(() => {  
  document.getElementById("splash").style.display = "unset";   
  },500)
  }
}, [showsplash])

React.useEffect(() => {
  if (showauth) {
  setTimeout(() => {  
  document.getElementById("auth").style.display = "unset";
  //document.documentElement.style.setProperty('--background', "url('https://cdn.pixabay.com/photo/2017/06/03/20/12/art-2369664_1280.jpg')");
  document.documentElement.style.setProperty('--background', "url('https://cdn.pixabay.com/photo/2019/04/26/17/47/color-4158152_1280.jpg')");
  },500)  
  } else {
  setTimeout(() => {  
  document.getElementById("auth").style.display = "none";  
  document.documentElement.style.setProperty('--background', '#282828');
  },500)  
  }
}, [showauth])

  return (
    <div className="container" id="container">
      <Head>
        <title>The Next Desktop Environment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="notch">
      <Notch />
      </div>
      
      <div id="splash">
      <Zoom in={showsplash}>
        <div><Splash /></div>
      </Zoom> 
      </div>
      
      <div id="auth">
      <Zoom in={showauth}>
        <div><Auth /></div>
      </Zoom> 
      </div>
    </div>
  )
}
