import Head from 'next/head'
import Splash from './splash.js'
import Auth from './auth.js'
import * as React from 'react'
import { Zoom } from '@mui/material'

export default function Home() {

const [showsplash,setSplash] = React.useState(true)
const [showauth,setAuth] = React.useState(false)
 
React.useEffect(() => {
setTimeout(() => {
  setAuth(true)
  setSplash(false)},2000)
})

React.useEffect(() => {
  if(!showsplash) {
  document.getElementById("splash").style.display = "none";
  } else {
  document.getElementById("splash").style.display = "unset";   
  }
}, [showsplash])

React.useEffect(() => {
  if (showauth) {
  document.getElementById("auth").style.display = "unset";
  document.documentElement.style.setProperty('--background', "url('https://cdn.pixabay.com/photo/2021/08/26/10/51/cliff-6575844_1280.jpg')");
  } else {
  document.getElementById("auth").style.display = "none";  
  document.documentElement.style.setProperty('--background', '#282828');
  }
}, [showauth])

  return (
    <div className="container">
      <Head>
        <title>The Next Desktop Environment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div id="splash">
      <Zoom in={showsplash}>
        <div><Splash /></div>
      </Zoom> 
      </div>
      
      <div id="auth">
      <Zoom in={showauth}>
        <div><Auth /></div>
      </Zoom> 
      </div>
    </div>
  )
}
